[module]
[[module.imports]]
  path = 'github.com/alex-shpak/hugo-book'


baseURL = 'https://mxro.github.io/code-at-scale/'
languageCode = 'en-us'
title = 'Code at Scale'

theme = 'hugo-book'

staticDir = ['static/images', 'content/docs/images']

relativeURLs = true

# Book theme config

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

disablePathToLower = true

# (Optional) Set Google Analytics if you use it to track your website.
# Always put it on the top of the configuration file, otherwise it won't work
# googleAnalytics = "UA-XXXXXXXXX-X"

[markup.goldmark.renderer]
  unsafe = true
